### PR TITLE
Add reference to blogpost introducing skorecard

### PR DESCRIPTION
**Pull request by timvink**

### CODE REVIEW

**Comment by timvink** [comment]
@orchardbirds the blogpost introducing skorecard is published :)

**Comment by timvink** [comment]
Btw, I just pushed https://github.com/ing-bank/skorecard/commit/e70f8fcc11743da93064695e7de7c65d8599b375 to `master`.. sorry, meant for it to be a PR..

**Comment by timvink** [comment]
@orchardbirds bump :)

**Comment by orchardbirds** [comment]
uiteindelijk ;)

**Pull request merged**
